TeamCommerce/backend-server

.github/workflows/CI_gradle.yml, build.gradle, src/main/java/com/commerce/backendserver/api/presentation/member/MemberController.java, src/test/java/com/commerce/backendserver/api/member/MemberControllerTest.java
- #1
- Gradle CI 자동화 파이프 라인 구축
- Jacoco Code Coverage 자동화 구축
- 테스트 전체 성공시 PR Comment
- 테스트가 하나라도 실패할 시 PR Comment
=> feat: Automated Gradle CI / Code Coverage

.github/PULL_REQUEST_TEMPLATE.md, .github/release-drafter-config.yml, .github/workflows/assign-workflow.yml, .github/workflows/labeler.yml, .github/workflows/release-drafter.yml
- #1 
- 릴리즈 드래프터를 활용해, `master` 브랜치 푸쉬[머지] 이벤트 발생 시 릴리즈를 업데이트 합니다.
- 추후 개발 서버 배포와 함께, 릴리즈 수정 예정
- PR 템플릿
- Assign Workflow로 코드리뷰어 자동 매칭
=> chore: CI / Add Release Drafter, PR Template, Labeler, Reviwer Assign

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/CI_assign_reviewer.yml, .github/workflows/CI_gradle.yml, build.gradle, src/main/java/com/commerce/backendserver/api/presentation/member/MemberController.java, src/test/java/com/commerce/backendserver/api/member/MemberControllerTest.java
- #1 
- Auto review yml config 수정
- Labeler 적용 테스트
=> fix: CI / Release Drafter, Labeler, Reviwer Assign (#1)

.github/workflows/CI_gradle.yml, README.md, build.gradle
=> chore: Add Code Coverage Badge on README.md

.github/release-drafter-config.yml
- #9 
- Release Drafter가 NEXT_PATCH_VERSION만을 참조해, 정상적으로 생성되지 않는 이슈 수정
-
=> fix: Release Drafter

.github/workflows/CI_release-drafter.yml
- #9
- Release Drafter가 정상적으로 기능하는지 테스트 하기 위한 PR.
=> test: Release Drafter

src/test/java/com/commerce/backendserver/api/member/MemberControllerTest.java
- #9
- Release Drafter 적용을 위한 테스트케이스 추가
-
=> feat: Add Test Codes For Test Release Drafter (#9)

src/test/java/com/commerce/backendserver/api/member/MemberControllerTest.java
=> feat: Patch Release (#14)

build.gradle
- #16 
- submodule 커밋을 업데이트 ->`478825d`
- 자동화 환경에서 build시 서브모듈 내 yml 파일을 복사하지 않는 이슈를 수정.
=> chore: repair to work copyGitSubmodule automated

.github/workflows/CI_assign-reviewer.yml, .github/workflows/CI_gradle.yml
- #20 
- Assign 트리거를 변경합니다 [ 수정 커밋 시에도 알릴 수 있도록 ]
- CI 테스트를 빌드로 변경합니다.
- 추후 master 푸쉬에 한해 분기하여, CD 배포가 진행될 수 있도록
=> feat: Inhance CI Logic

src/main/java/com/commerce/backendserver/auth/application/CustomOAuth2LoginService.java, src/main/java/com/commerce/backendserver/auth/application/filter/JwtAuthenticationFilter.java, src/main/java/com/commerce/backendserver/auth/application/handler/CustomOAuthLoginSuccessHandler.java, src/main/java/com/commerce/backendserver/auth/domain/Token.java, src/main/java/com/commerce/backendserver/auth/infra/jwt/JwtProvider.java, src/main/java/com/commerce/backendserver/global/config/AuditingConfig.java, src/test/java/com/commerce/backendserver/auth/domain/TokenQueryRepositoryTest.java, src/test/java/com/commerce/backendserver/auth/domain/TokenTest.java, src/test/java/com/commerce/backendserver/auth/infra/GoogleUserProfileTest.java, src/test/java/com/commerce/backendserver/auth/infra/KakaoUserProfileTest.java, src/test/java/com/commerce/backendserver/auth/infra/OAuthProfileFactoryTest.java, src/test/java/com/commerce/backendserver/auth/infra/OAuthTypeTest.java, src/test/java/com/commerce/backendserver/auth/infra/UserPrincipalTest.java, src/test/java/com/commerce/backendserver/common/base/RepositoryTestBase.java, src/test/java/com/commerce/backendserver/common/fixture/MemberFixture.java, src/test/java/com/commerce/backendserver/common/utils/TokenUtils.java, src/test/java/com/commerce/backendserver/global/exception/ApiExceptionHandlerTest.java, src/test/java/com/commerce/backendserver/member/domain/MemberQueryRepositoryTest.java, src/test/java/com/commerce/backendserver/member/domain/MemberTest.java
- #32 
- Auth - Infra layer 테스팅
- Member, Token  - Domain layer(entity, repository) 테스팅
- DisplayName 에 대한 컨벤션이 필요할거같아요. 상의 후에 다시 설정하도록 하겠습니다.
- 이 후에 auth - application layer 에 대해서 테스팅 할 예정입니다.
=> feat: Test infra layer of auth, domain layer of member and token

src/main/java/com/commerce/backendserver/auth/infra/jwt/JwtProvider.java, src/main/java/com/commerce/backendserver/global/exception/ApiExceptionHandler.java, src/test/java/com/commerce/backendserver/auth/application/filter/JwtFilterTest.java, src/test/java/com/commerce/backendserver/auth/infra/jwt/JwtProviderTest.java, src/test/java/com/commerce/backendserver/auth/infra/oauth/GoogleUserProfileTest.java, src/test/java/com/commerce/backendserver/auth/infra/oauth/KakaoUserProfileTest.java, src/test/java/com/commerce/backendserver/auth/infra/oauth/OAuthProfileFactoryTest.java, src/test/java/com/commerce/backendserver/auth/infra/oauth/OAuthTypeTest.java, src/test/java/com/commerce/backendserver/auth/infra/oauth/UserPrincipalTest.java, src/test/java/com/commerce/backendserver/common/controller/TestController.java, src/test/java/com/commerce/backendserver/common/utils/TokenUtils.java, src/test/java/com/commerce/backendserver/global/exception/ApiExceptionHandlerTest.java
- #32 
- JwtProvider 테스트
- JwtAuthenticationFilter 테스트
- oauth 로직에 관한 테스팅은 이런식의 단위 테스팅이 현재로선 방법을 못찾아서 우선 제외했습니다.
=> feat: Test JwtProvider and JwtAuthenticationFilter

src/main/java/com/commerce/backendserver/global/exception/error/GlobalError.java, src/main/java/com/commerce/backendserver/image/domain/Image.java, src/main/java/com/commerce/backendserver/image/exception/ImageError.java, src/main/java/com/commerce/backendserver/product/application/ProductFindService.java, src/main/java/com/commerce/backendserver/product/application/ProductService.java, src/main/java/com/commerce/backendserver/product/domain/Product.java, src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java, src/main/java/com/commerce/backendserver/product/domain/ProductImage.java, src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java, src/main/java/com/commerce/backendserver/product/domain/constants/ProductBrand.java, src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java, src/main/java/com/commerce/backendserver/product/domain/option/SelectionOption.java, src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java, src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPeriodAttribute.java, src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java, src/main/java/com/commerce/backendserver/product/dto/request/ProductCreateRequest.java, src/main/java/com/commerce/backendserver/product/exception/ProductError.java
- #39 
- #40 
- 코드리뷰 내용을 반영한 수정 내용입니다.
=> feat: Enhance Product Entity

src/main/java/com/commerce/backendserver/global/exception/error/GlobalError.java, src/main/java/com/commerce/backendserver/image/domain/Image.java, src/main/java/com/commerce/backendserver/image/exception/ImageError.java, src/main/java/com/commerce/backendserver/product/application/ProductFindService.java, src/main/java/com/commerce/backendserver/product/application/ProductRegisterService.java, src/main/java/com/commerce/backendserver/product/application/ProductService.java, src/main/java/com/commerce/backendserver/product/domain/Product.java, src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java, src/main/java/com/commerce/backendserver/product/domain/ProductImage.java, src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java, src/main/java/com/commerce/backendserver/product/domain/constants/ProductBrand.java, src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java, src/main/java/com/commerce/backendserver/product/domain/option/SelectionOption.java, src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java, src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPeriodAttribute.java, src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java, src/main/java/com/commerce/backendserver/product/dto/request/ProductCreateRequest.java, src/main/java/com/commerce/backendserver/product/exception/ProductError.java, src/main/java/com/commerce/backendserver/product/presentation/ProductSearchController.java
- #39 
- Product 도메인에서 누락되었던 Image 컬럼을 추가합니다.
- Product 및 하위 도메인의 Constructor과 기본 Validation 로직을 추가합니다.
- 상기 작업사항 외 내용 푸쉬는 추후 개발내용입니다.
=> feat: Add Constructor / Validation Method for Product Entity

.gitignore, build.gradle, src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java, src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java, src/main/java/com/commerce/backendserver/product/domain/option/SelectionOption.java, src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java, src/test/java/com/commerce/backendserver/member/domain/MemberTest.java
- #50 
- QueryDSL을 해당 프로젝트에 적용합니다.
- JacocoTestReport가 Q* 형식의 QueryDSL 디렉토리를 테스트하지 않도록 설정합니다.
- 추가적으로, Fixture, Config, Dto, Exception, SpringApplication등 테스트 불필요 파일에 대한 테스트 또한 제외합니다.
=> feat: Init QueryDSL, Modify Jacoco Test Report

src/main/java/com/commerce/backendserver/review/domain/Review.java, src/main/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfo.java, src/main/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoList.java, src/main/java/com/commerce/backendserver/review/domain/additionalinfo/constants/InfoName.java, src/main/java/com/commerce/backendserver/review/domain/likereview/LikeReview.java, src/main/java/com/commerce/backendserver/review/exception/ReviewError.java
- #53 
- 리뷰 ENTITY 구현
- 리뷰 좋아요 ENTITY 구현
- Image 는 h-beeen 의 작업 이후에 추가 예정
=> feat: Define review entity

src/main/java/com/commerce/backendserver/review/application/dto/response/AdditionalInfoStatistic.java, src/main/java/com/commerce/backendserver/review/application/dto/response/RatioStatistic.java, src/main/java/com/commerce/backendserver/review/application/dto/response/ReviewStatistics.java, src/main/java/com/commerce/backendserver/review/domain/ReviewQueryRepository.java
- #69 
- 응답스펙 record 구현
- ReviewQueryRepository 선언
- Response 에 대해 고민을 많이 해봤어요. Response 자체는 가볍게 가는게 어떨까 해서 `record` 로 구현해봤습니다. 이전 리뷰에서 class 로 통일하자고 제가 말해놓고 부끄럽긴한데 번복해봅니다 🙏 
- 물론 제 **의견**입니다. `class` 로 진행해도 상관없을거같아요. 리뷰하시고 의견 부탁드려요.
=> feat: 리뷰 통계정보 조회 API 응답스펙 구현

src/main/java/com/commerce/backendserver/product/infra/persistence/ProductQueryRepository.java, src/main/java/com/commerce/backendserver/review/application/ReviewService.java, src/main/java/com/commerce/backendserver/review/exception/ReviewError.java, src/test/java/com/commerce/backendserver/product/infra/persistence/ProductQueryRepositoryTest.java, src/test/java/com/commerce/backendserver/review/application/ReviewServiceTest.java
- #87 
- ProductOption 를 포함한 Product 단건 조회 쿼리 구현 (9421c12b1e642dfaacdd24d284d79310e2b6fda9)
- 리뷰 등록 서비스로직에 ProductOptionId 검증로직 추가 (604f394d1a51a725a17e07cc13b6acfb32ee70f4)
- 구현한 쿼리, 수정된 서비스 로직 테스팅(604f394d1a51a725a17e07cc13b6acfb32ee70f4, 9421c12b1e642dfaacdd24d284d79310e2b6fda9)
=> feat: 리뷰 등록 서비스 로직에 ProductOptionId 검증 로직 추가

src/main/java/com/commerce/backendserver/auth/application/OAuthService.java, src/main/java/com/commerce/backendserver/auth/domain/OAuthUriGenerator.java, src/main/java/com/commerce/backendserver/auth/exception/AuthError.java, src/main/java/com/commerce/backendserver/auth/infra/oauth/google/GoogleUriGenerator.java, src/main/java/com/commerce/backendserver/auth/infra/oauth/kakao/KakaoUriGenerator.java, src/main/java/com/commerce/backendserver/auth/presentation/OAuthApiController.java, src/test/java/com/commerce/backendserver/auth/integration/OAuthApiTest.java, src/test/java/com/commerce/backendserver/auth/integration/fixture/OAuthRequestFixture.java, src/test/java/com/commerce/backendserver/common/base/IntegrationTestBase.java, src/test/java/com/commerce/backendserver/common/fixture/CommonRequestFixture.java
- #100 
- 소셜로그인 API 통합테스트
- restdocs-swagger 를 통해 명세
* 로컬환경에서는 확인해보실 수 있습니다
=> feat: 소셜로그인 API 명세

.github/workflows/CI-AssignReviewer.yml, .github/workflows/CICD-Gradle.yml
=> fix: GithubAction Workflow 오탈자 수정
